### ISSUE TITLE
Experiencing Error in Script Execution. 

### ISSUE THREAD

**Issue by BenSamy2020** [bittremieux/falcon#11]
Greetings,

Firstly, I would like to thank you for providing this open-source tool. I am new to programming and was trying to run the package you provided. I am consistently experiencing error. Please refer to screenshot of error message below. Please do advise me on how to troubleshoot.

Regards,
Ben
![image](https://user-images.githubusercontent.com/69944967/126738849-963f105b-9fac-4052-8914-3ba5a5f12246.png)

**Comment by KilianMaes** [comment]
Hi,

As it is specified in the readme of this repository (section "Installation"), falcon should be run on Linux or OSX but not Windows (as explained by @bittremieux  in issue #9). Many Linux distributions are freely available and can be installed on a computer (possibly in dual boot with windows) or executed within a virtual machine (see VirtualBox).

Best regards, 

Kilian

**Comment by bittremieux** [comment]
The error you see is because the input directory has not been specified correctly. In the example on the main page the directory with peak files is `peak/`, in your case this would be `E:\MS_RAW_Files\...`, so without the `peak/` prefix.

However, even when specifying the input peak files correctly, falcon indeed only runs on Linux or OS X, not on Windows. Possibly the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10) could be used to run falcon in your Windows environment without needing a dual-boot system, but this functionality has not been tested.
